// Catálogos padrão por segmento
// Carregados via POST /catalog/seed no onboarding

export const CATALOG_SEEDS = {


  ELETRICA: [
    { code: 'EL-01', description: 'Ponto elétrico tomada 2P+T bivolt', unit: 'PT', category: 'SERVICO', defaultPrice: 280 },
    { code: 'EL-02', description: 'Ponto elétrico tomada 2P+T 20A (ar condicionado/chuveiro)', unit: 'PT', category: 'SERVICO', defaultPrice: 350 },
    { code: 'EL-03', description: 'Ponto de iluminação teto (simples)', unit: 'PT', category: 'SERVICO', defaultPrice: 220 },
    { code: 'EL-04', description: 'Ponto de iluminação com acionamento (interruptor + ponto)', unit: 'PT', category: 'SERVICO', defaultPrice: 320 },
    { code: 'EL-05', description: 'Ponto de iluminação three-way (dois interruptores)', unit: 'PT', category: 'SERVICO', defaultPrice: 420 },
    { code: 'EL-06', description: 'Fio flexível 2,5mm² (cabo PP ou sólido)', unit: 'ML', category: 'MATERIAL', defaultPrice: 4.5 },
    { code: 'EL-07', description: 'Fio flexível 4,0mm²', unit: 'ML', category: 'MATERIAL', defaultPrice: 7.2 },
    { code: 'EL-08', description: 'Fio flexível 6,0mm²', unit: 'ML', category: 'MATERIAL', defaultPrice: 10.8 },
    { code: 'EL-09', description: 'Eletroduto PVC rígido 3/4" (por metro)', unit: 'ML', category: 'MATERIAL', defaultPrice: 5.5 },
    { code: 'EL-10', description: 'Canaleta PVC 20x10mm (por metro)', unit: 'ML', category: 'MATERIAL', defaultPrice: 8.0 },
    { code: 'EL-11', description: 'Disjuntor monopolar 10A', unit: 'UNID', category: 'MATERIAL', defaultPrice: 22 },
    { code: 'EL-12', description: 'Disjuntor monopolar 20A', unit: 'UNID', category: 'MATERIAL', defaultPrice: 24 },
    { code: 'EL-13', description: 'Disjuntor bipolar 32A', unit: 'UNID', category: 'MATERIAL', defaultPrice: 65 },
    { code: 'EL-14', description: 'Quadro de distribuição 12 disjuntores (embutir)', unit: 'UNID', category: 'MATERIAL', defaultPrice: 280 },
    { code: 'EL-15', description: 'Quadro de distribuição 24 disjuntores (embutir)', unit: 'UNID', category: 'MATERIAL', defaultPrice: 420 },
    { code: 'EL-16', description: 'DPS (Dispositivo de Proteção contra Surtos) bipolar', unit: 'UNID', category: 'MATERIAL', defaultPrice: 120 },
    { code: 'EL-17', description: 'DR (Dispositivo Residual) 25A — 30mA', unit: 'UNID', category: 'MATERIAL', defaultPrice: 95 },
    { code: 'EL-18', description: 'Instalação de ventilador de teto', unit: 'UNID', category: 'SERVICO', defaultPrice: 180 },
    { code: 'EL-19', description: 'Instalação de luminária (material não incluso)', unit: 'UNID', category: 'SERVICO', defaultPrice: 120 },
    { code: 'EL-20', description: 'ART — Anotação de Responsabilidade Técnica', unit: 'UNID', category: 'SERVICO', defaultPrice: 350 },
    { code: 'EL-21', description: 'Laudo elétrico / vistoria com relatório', unit: 'UNID', category: 'SERVICO', defaultPrice: 600 },
    { code: 'EL-22', description: 'SPDA — Para-raios (projeto + instalação)', unit: 'VB', category: 'SERVICO', defaultPrice: 3500 },
  ],

  CONSTRUCAO_CIVIL: [
    { code: 'CC-01', description: 'Alvenaria de tijolo cerâmico 9x19x19cm (argamassa inclusa)', unit: 'M2', category: 'SERVICO', defaultPrice: 95 },
    { code: 'CC-02', description: 'Alvenaria de bloco de concreto 14x19x39cm', unit: 'M2', category: 'SERVICO', defaultPrice: 115 },
    { code: 'CC-03', description: 'Reboco externo (argamassa industrializada)', unit: 'M2', category: 'SERVICO', defaultPrice: 45 },
    { code: 'CC-04', description: 'Reboco interno (gesso liso)', unit: 'M2', category: 'SERVICO', defaultPrice: 38 },
    { code: 'CC-05', description: 'Emboço paulista (1 camada)', unit: 'M2', category: 'SERVICO', defaultPrice: 32 },
    { code: 'CC-06', description: 'Contrapiso de argamassa (5cm)', unit: 'M2', category: 'SERVICO', defaultPrice: 55 },
    { code: 'CC-07', description: 'Piso cerâmico — assentamento (material cliente)', unit: 'M2', category: 'SERVICO', defaultPrice: 65 },
    { code: 'CC-08', description: 'Piso cerâmico — assentamento c/ material (porcelanato 60x60)', unit: 'M2', category: 'SERVICO', defaultPrice: 220 },
    { code: 'CC-09', description: 'Revestimento cerâmico parede (material cliente)', unit: 'M2', category: 'SERVICO', defaultPrice: 70 },
    { code: 'CC-10', description: 'Laje pré-moldada (fornecimento + instalação)', unit: 'M2', category: 'SERVICO', defaultPrice: 280 },
    { code: 'CC-11', description: 'Concreto usinado fck 25 MPa — fornecimento e lançamento', unit: 'M3', category: 'MATERIAL', defaultPrice: 680 },
    { code: 'CC-12', description: 'Estrutura metálica (treliça/pillar) — fabricação e montagem', unit: 'KG', category: 'SERVICO', defaultPrice: 28 },
    { code: 'CC-13', description: 'Impermeabilização com manta asfáltica 3mm', unit: 'M2', category: 'SERVICO', defaultPrice: 120 },
    { code: 'CC-14', description: 'Impermeabilização com argamassa bicomponente', unit: 'M2', category: 'SERVICO', defaultPrice: 75 },
    { code: 'CC-15', description: 'Demolição de parede de alvenaria', unit: 'M2', category: 'SERVICO', defaultPrice: 55 },
    { code: 'CC-16', description: 'Remoção e descarte de entulho (caçamba)', unit: 'UNID', category: 'SERVICO', defaultPrice: 800 },
    { code: 'CC-17', description: 'ART/RRT — Responsabilidade Técnica', unit: 'UNID', category: 'SERVICO', defaultPrice: 400 },
    { code: 'CC-18', description: 'Projeto arquitetônico residencial (por m² construído)', unit: 'M2', category: 'SERVICO', defaultPrice: 35 },
    { code: 'CC-19', description: 'Mão de obra — pedreiro + ajudante (diária)', unit: 'HRS', category: 'MAO_DE_OBRA', defaultPrice: 480 },
    { code: 'CC-20', description: 'BDI — Bonificações e Despesas Indiretas', unit: 'VB', category: 'SERVICO', defaultPrice: 0 },
  ],

  HIDRAULICA: [
    { code: 'HID-01', description: 'Ponto de água fria (instalação completa)', unit: 'PT', category: 'SERVICO', defaultPrice: 250 },
    { code: 'HID-02', description: 'Ponto de água quente (CPVC ou PPR)', unit: 'PT', category: 'SERVICO', defaultPrice: 320 },
    { code: 'HID-03', description: 'Ponto de esgoto (saída + caixa sifonada)', unit: 'PT', category: 'SERVICO', defaultPrice: 280 },
    { code: 'HID-04', description: 'Ponto de gás (tubulação + registro)', unit: 'PT', category: 'SERVICO', defaultPrice: 380 },
    { code: 'HID-05', description: 'Tubulação PVC soldável 3/4" (por metro)', unit: 'ML', category: 'MATERIAL', defaultPrice: 12 },
    { code: 'HID-06', description: 'Tubulação PVC soldável 1" (por metro)', unit: 'ML', category: 'MATERIAL', defaultPrice: 18 },
    { code: 'HID-07', description: 'Tubulação PPR 20mm (por metro)', unit: 'ML', category: 'MATERIAL', defaultPrice: 22 },
    { code: 'HID-08', description: 'Tubulação PPR 25mm (por metro)', unit: 'ML', category: 'MATERIAL', defaultPrice: 30 },
    { code: 'HID-09', description: 'Instalação de vaso sanitário completo', unit: 'UNID', category: 'SERVICO', defaultPrice: 280 },
    { code: 'HID-10', description: 'Instalação de pia (cuba + sifão + flexível)', unit: 'UNID', category: 'SERVICO', defaultPrice: 220 },
    { code: 'HID-11', description: 'Instalação de chuveiro elétrico', unit: 'UNID', category: 'SERVICO', defaultPrice: 180 },
    { code: 'HID-12', description: 'Instalação de aquecedor a gás (passagem)', unit: 'UNID', category: 'SERVICO', defaultPrice: 380 },
    { code: 'HID-13', description: 'Caixa d\'água 1.000L — instalação e ligação', unit: 'UNID', category: 'SERVICO', defaultPrice: 650 },
    { code: 'HID-14', description: 'Registro de gaveta 3/4" (material + instalação)', unit: 'UNID', category: 'MATERIAL', defaultPrice: 85 },
    { code: 'HID-15', description: 'Teste hidrostático (emissão de laudo)', unit: 'UNID', category: 'SERVICO', defaultPrice: 350 },
    { code: 'HID-16', description: 'Desentupimento — ramal interno', unit: 'UNID', category: 'SERVICO', defaultPrice: 280 },
  ],

  PINTURA: [
    { code: 'PIN-01', description: 'Pintura parede interna — tinta látex PVA (2 demãos)', unit: 'M2', category: 'SERVICO', defaultPrice: 18 },
    { code: 'PIN-02', description: 'Pintura parede interna — tinta acrílica premium (2 demãos)', unit: 'M2', category: 'SERVICO', defaultPrice: 28 },
    { code: 'PIN-03', description: 'Pintura teto — tinta látex branca (2 demãos)', unit: 'M2', category: 'SERVICO', defaultPrice: 22 },
    { code: 'PIN-04', description: 'Pintura fachada — tinta acrílica c/ textura', unit: 'M2', category: 'SERVICO', defaultPrice: 65 },
    { code: 'PIN-05', description: 'Pintura fachada — tinta acrílica lisa (3 demãos)', unit: 'M2', category: 'SERVICO', defaultPrice: 45 },
    { code: 'PIN-06', description: 'Pintura epóxi — piso industrial', unit: 'M2', category: 'SERVICO', defaultPrice: 75 },
    { code: 'PIN-07', description: 'Massa corrida PVA parede (preparação)', unit: 'M2', category: 'SERVICO', defaultPrice: 15 },
    { code: 'PIN-08', description: 'Massa corrida acrílica (preparação fachada)', unit: 'M2', category: 'SERVICO', defaultPrice: 20 },
    { code: 'PIN-09', description: 'Selador acrílico (1 demão)', unit: 'M2', category: 'MATERIAL', defaultPrice: 8 },
    { code: 'PIN-10', description: 'Lixamento e limpeza de superfície', unit: 'M2', category: 'SERVICO', defaultPrice: 10 },
    { code: 'PIN-11', description: 'Aplicação de textura — graveto', unit: 'M2', category: 'SERVICO', defaultPrice: 55 },
    { code: 'PIN-12', description: 'Aplicação de textura — desempenada', unit: 'M2', category: 'SERVICO', defaultPrice: 48 },
    { code: 'PIN-13', description: 'Pintura grade / portão (esmalte sintético)', unit: 'M2', category: 'SERVICO', defaultPrice: 65 },
    { code: 'PIN-14', description: 'Sobretaxa — cor especial / mistura personalizada', unit: 'VB', category: 'SERVICO', defaultPrice: 200 },
  ],

  AR_CONDICIONADO: [
    { code: 'AR-01', description: 'Instalação split 9.000 BTUs (mão de obra)', unit: 'UNID', category: 'SERVICO', defaultPrice: 380 },
    { code: 'AR-02', description: 'Instalação split 12.000 BTUs (mão de obra)', unit: 'UNID', category: 'SERVICO', defaultPrice: 420 },
    { code: 'AR-03', description: 'Instalação split 18.000 BTUs (mão de obra)', unit: 'UNID', category: 'SERVICO', defaultPrice: 480 },
    { code: 'AR-04', description: 'Instalação split 24.000 BTUs (mão de obra)', unit: 'UNID', category: 'SERVICO', defaultPrice: 550 },
    { code: 'AR-05', description: 'Fornecimento + instalação split 9.000 BTUs inverter', unit: 'UNID', category: 'EQUIPAMENTO', defaultPrice: 2200 },
    { code: 'AR-06', description: 'Fornecimento + instalação split 12.000 BTUs inverter', unit: 'UNID', category: 'EQUIPAMENTO', defaultPrice: 2800 },
    { code: 'AR-07', description: 'Fornecimento + instalação split 18.000 BTUs inverter', unit: 'UNID', category: 'EQUIPAMENTO', defaultPrice: 3600 },
    { code: 'AR-08', description: 'Tubulação de cobre 1/4" + 1/2" (por metro, c/ isolamento)', unit: 'ML', category: 'MATERIAL', defaultPrice: 45 },
    { code: 'AR-09', description: 'Dreno PVC 3/4" (por metro)', unit: 'ML', category: 'MATERIAL', defaultPrice: 12 },
    { code: 'AR-10', description: 'Suporte de teto/parede para unidade interna', unit: 'UNID', category: 'MATERIAL', defaultPrice: 85 },
    { code: 'AR-11', description: 'Suporte para unidade externa (condensadora)', unit: 'UNID', category: 'MATERIAL', defaultPrice: 120 },
    { code: 'AR-12', description: 'Manutenção preventiva — limpeza geral split (mensal)', unit: 'UNID', category: 'SERVICO', defaultPrice: 180 },
    { code: 'AR-13', description: 'Manutenção preventiva — limpeza geral split (trimestral)', unit: 'UNID', category: 'SERVICO', defaultPrice: 220 },
    { code: 'AR-14', description: 'Recarga de gás R410A', unit: 'UNID', category: 'SERVICO', defaultPrice: 350 },
    { code: 'AR-15', description: 'Instalação cassete 36.000 BTUs (teto)', unit: 'UNID', category: 'SERVICO', defaultPrice: 1200 },
  ],

  OUTRO: [
    { code: 'SRV-01', description: 'Serviço geral — mão de obra', unit: 'HRS', category: 'MAO_DE_OBRA', defaultPrice: 0 },
    { code: 'SRV-02', description: 'Material — fornecimento', unit: 'UNID', category: 'MATERIAL', defaultPrice: 0 },
    { code: 'SRV-03', description: 'Visita técnica / consultoria', unit: 'HRS', category: 'SERVICO', defaultPrice: 0 },
  ]
}
